### PR TITLE
fix for crash with inpainting model introduced by #1866

### LINKED ISSUE #1907: [bug]: AttributeError: 'NoneType' object has no attribute 'tokens_count_including_eos_bos'
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64

### What happened?

When using using the inpainting model on the unified canvas, I get the following error:
tokens_count_including_eos_bos

> Traceback (most recent call last):
>   File "/Users/xxxxxx/Documents/invokeAI-installer/backend/invoke_ai_web_server.py", line 1124, in generate_images
>     self.generate.prompt2image(
>   File "/Users/xxxxxx/Documents/invokeAI-installer/ldm/generate.py", line 488, in prompt2image
>     results = generator.generate(
>   File "/Users/xxxxxx/Documents/invokeAI-installer/ldm/invoke/generator/base.py", line 98, in generate
>     image = make_image(x_T)
>   File "/Users/xxxxxx/Documents/invokeAI-installer/ldm/invoke/generator/omnibus.py", line 123, in make_image
>     samples, _ = sampler.sample(
>   File "/Users/xxxxxx/Documents/invokeAI-installer/installer_files/env/envs/invokeai/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "/Users/xxxxxx/Documents/invokeAI-installer/ldm/models/diffusion/ksampler.py", line 211, in sample
>     attention_map_token_ids = range(1, extra_conditioning_info.tokens_count_including_eos_bos - 1)
> AttributeError: 'NoneType' object has no attribute 'tokens_count_including_eos_bos'

The error appears to only happen when using the samplers that start with k_*. 
"ddim" and "plms" don't cause the error to happen. 

### Screenshots

_No response_

### Additional context

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by damian0815**
fixes #1907

### CODE REVIEW

**Review by lstein — APPROVED** [review]
LGTM. Thanks for finding and fixing.
