### ISSUE TITLE
[bug]: Error When Outpainting in Unified Canvas

### ISSUE THREAD

**Issue by brainbent** [invoke-ai/InvokeAI#3092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What version did you experience this issue on?

2.3.2 + 3.0.0+a0

### What happened?

When trying to outpaint an image in the Unifed Canvas tab, it starts the process and then ends with this error:

```
Inpaint.get_make_image.<locals>.make_image() missing 1 required positional argument: 'seed'

Traceback (most recent call last):
  File "D:\StableDiffusion AI\InvokeAI-NewBuild\.venv\lib\site-packages\invokeai\backend\web\invoke_ai_web_server.py", line 1312, in generate_images
    self.generate.prompt2image(
  File "D:\StableDiffusion AI\InvokeAI-NewBuild\.venv\lib\site-packages\invokeai\backend\generate.py", line 505, in prompt2image
    results = generator.generate(
  File "D:\StableDiffusion AI\InvokeAI-NewBuild\.venv\lib\site-packages\invokeai\backend\generator\base.py", line 378, in generate
    image = make_image(x_T, seed)
  File "D:\StableDiffusion AI\InvokeAI-NewBuild\.venv\lib\site-packages\invokeai\backend\generator\inpaint.py", line 340, in make_image
    result = self.seam_paint(
  File "D:\StableDiffusion AI\InvokeAI-NewBuild\.venv\lib\site-packages\invokeai\backend\generator\inpaint.py", line 195, in seam_paint
    result = make_image(seam_noise)
TypeError: Inpaint.get_make_image.<locals>.make_image() missing 1 required positional argument: 'seed'
```

I've played with a number of options in an attempt to fix it, but nothing's working... :(

### Screenshots

![8141880d-81ca-4167-b058-19b773e26f34](https://user-images.githubusercontent.com/50431896/229266660-09f4649f-277b-4c6e-b7c4-77e8a3e28437.png)

### Contact Details

serenity@brainbent.dev

**Comment by Barafu** [comment]
It may be a combination of a complex prompt with bad syntax and the model. Did you try to outpaint with default SD model and an empty prompt? If that works, the culprit is in the prompt. At least, multiple brackets are wrong. 

Offtopic, but you may find this trick useful: sometimes AI does not understand some simple adjective like "car with small wheels". In this case, putting "car" in positive prompt and simply "wheels" in negative prompt will help.

**Comment by brainbent** [comment]
> It may be a combination of a complex prompt with bad syntax and the model. Did you try to outpaint with default SD model and an empty prompt? If that works, the culprit is in the prompt. 

It started working with the 2.3.3 update (even though changes to the code had nothing to do with the Unified Canvas?!

> At least, multiple brackets are wrong.

I have **_no_** idea where I got the multiple brackets for emphasis from! Been using them for that purpose since I started with AI art a couple of months ago...
 
> Offtopic, but you may find this trick useful: sometimes AI does not understand some simple adjective like "car with small wheels". In this case, putting "car" in positive prompt and simply "wheels" in negative prompt will help.

Interesting! I'll give that a go. Thanks :)
