### ISSUE TITLE
[bug]: Unified canvas doesn't work on firefox

### ISSUE THREAD

**Issue by jakehl** [invoke-ai/InvokeAI#1869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### VRAM

12GB

### What happened?

On firefox, when using the webUI, painting on the unified canvas no longer works. It works fine on chrome.

When I click on the canvas with the brush or eraser selected I get the following error in the developer console.
```
Uncaught TypeError: e.layerState.objects.findLast is not a function
```

**Comment by jakehl** [comment]
I've got a working fix. I can submit a PR with a more refined version soon. 
Firefox doesn't seep to support the newish `findLast` functions on arrays. 

In `frontend/src/features/canvas/store/canvasSlice.ts` replace the `findLast` call with something along these lines. 

```typescript
      const findLastHack = (
        array: CanvasObject[],
        index: number,
        found?: CanvasMaskLine | CanvasBaseLine
      ): CanvasBaseLine | CanvasMaskLine | undefined => {
        if (index >= array.length) return found;
        const working = array[index];
        const newFound = isCanvasAnyLine(working) ? working : found
        return findLastHack(array, index + 1, newFound);
      };

      const lastLine = findLastHack(state.layerState.objects, 0)


      if (!lastLine) return;

      lastLine.points.push(...action.payload);

```

**Comment by blessedcoolant** [comment]
Is this breaking on the latest version of firefox? And feel free to make the PR. I'll review it. Thank you.

**Comment by jakehl** [comment]
I'll double check I'm up to date later today. Pretty sure I am though 👍

**Comment by jakehl** [comment]
My browser is up to date on my current machine, but trying on my other machine works fine. I'll chalk it up to an issue on my end as the firefox change logs definitely mention adding support for the feature.

**Comment by rmc135** [comment]
FYI, it's not just you. I have the same problem, and the exact same error in the dev console.

Latest version of FF, 102.5.0esr (64 bit), under Windows 8.1

(invokeAI is running on a separate machine, Ubuntu 22.04.1 LTS with 24GB VRAM)

Please continue to investigate!

**Comment by psychedelicious** [comment]
https://caniuse.com/mdn-javascript_builtins_array_findlast

I will update the compilation target to something more conservative to ensure this is polyfilled.

**Comment by jakehl** [comment]
If that doesn't work, I've a PR that I closed which also fixes the issue with a polyfill I wrote (It's better than my hack posted above lol). I'm happy to re-open.

@rmc135 for what it's worth, the findLast support wasn't added until firefox 103 or 104 iirc. With you being on esr it'll be a little while until you get built in support. Although I would say it's not a bad thing to support the esr releases as the bare minimum for invoke on firefox.

**Comment by psychedelicious** [comment]
I've PR'd a quick fix (polyfilling `Array.prototype.findLast()` via build plugin) in #1909. We can use additional functionality provided by this plugin if we need to broaden browser support at some point.

**Comment by rmc135** [comment]
After applying jakehl's temporary hack (which worked) I believe I updated to a newer official version, which would have overwritten that hack (it's not present in the old canvasSlice.ts I have backed up, and that file has the exact same timestamp as others in the directory). Everything has been working as expected for a couple of months. So there was a proper workaround officially merged into InvokeAI, right?

However... after an update to 2.3.1post2 the OP behaviour is back: Uncaught TypeError: e.layerState.objects.findLast is not a function

Currently using latest FF ESR version 102.8.0esr (64-bit)

**Comment by rmc135** [comment]
@jakehl many thanks, that works.

Just trying to figure out how/why a fix was merged (I believe?) but has regressed at some point.

**Comment by jakehl** [comment]
I've not dug into the code for a while, but based on previous discussion the polyfill has probably been removed.

**Comment by psychedelicious** [comment]
Oops, I had forgotten about the polyfill being needed. 

There was another issue with `Array.prototype.findLast` (it has no type definitions in typescript 4) and conflated the manual type defs with the polyfill. I removed the polyfill while doing a code cleanup. 

Will fix. Sorry.

**Comment by jakehl** [comment]
Pretty sure this is still a bug, Mr Bot.
